import { WritingPrompt } from '../../data/types';

export const a1WritingPrompts: WritingPrompt[] = [
  {
    id: 'wp-a1-1',
    topicIds: ['a1-verbs-present'],
    promptText: 'Schrijf een zin over waar je woont en wat je voor werk doet.',
    promptTextEn: 'Write a sentence about where you live and what you do for work.',
    targetGrammarPoints: ['present tense regular verb agreement (ik/jij/hij/wij forms)'],
  },
  {
    id: 'wp-a1-2',
    topicIds: ['a1-word-order'],
    promptText: 'Begin je zin met "Vandaag" en zeg iets over het weer.',
    promptTextEn: 'Start your sentence with "Vandaag" (today) and say something about the weather.',
    targetGrammarPoints: ['V2 word order after a fronted time adverb'],
  },
  {
    id: 'wp-a1-3',
    topicIds: ['a1-articles'],
    promptText: 'Beschrijf drie dingen in je huis. Gebruik "de" of "het" bij elk woord.',
    promptTextEn: 'Describe three things in your house. Use "de" or "het" with each word.',
    targetGrammarPoints: ['de/het article agreement'],
  },
  {
    id: 'wp-a1-4',
    topicIds: ['a1-pronouns', 'a1-possessives'],
    promptText: 'Schrijf twee zinnen over een vriend of vriendin: wat diegene doet, en iets dat van hen is.',
    promptTextEn: 'Write two sentences about a friend: something they do, and something that belongs to them.',
    targetGrammarPoints: ['subject vs. object pronouns', 'possessive agreement (zijn/haar)'],
  },
  {
    id: 'wp-a1-5',
    topicIds: ['a1-prepositions'],
    promptText: 'Beschrijf je ochtend met minstens twee voorzetsels (bijvoorbeeld: naar, op, met).',
    promptTextEn: 'Describe your morning using at least two prepositions (for example: naar, op, met).',
    targetGrammarPoints: ['preposition choice (in/op/naar/met/van/voor)'],
  },
  {
    id: 'wp-a1-6',
    topicIds: ['a1-negation'],
    promptText: 'Schrijf twee zinnen: één met "niet" en één met "geen".',
    promptTextEn: 'Write two sentences: one using "niet" and one using "geen".',
    targetGrammarPoints: ['niet vs. geen negation choice'],
  },
  {
    id: 'wp-a1-7',
    topicIds: ['a1-questions'],
    promptText: 'Bedenk drie vragen om aan een nieuwe vriend te stellen. Gebruik minstens één vraagwoord.',
    promptTextEn: 'Come up with three questions to ask a new friend. Use at least one question word.',
    targetGrammarPoints: ['question word order (verb-subject inversion)'],
  },
  {
    id: 'wp-a1-8',
    topicIds: ['a1-simple-past'],
    promptText: 'Schrijf twee zinnen over wat je gisteren deed, in de onvoltooid verleden tijd.',
    promptTextEn: 'Write two sentences about what you did yesterday, using the simple past tense.',
    targetGrammarPoints: ["t/d-verb simple past conjugation ('t kofschip rule)"],
  },
  {
    id: 'wp-a1-9',
    topicIds: ['a1-present-perfect'],
    promptText: 'Schrijf drie zinnen over wat je deze week al hebt gedaan.',
    promptTextEn: 'Write three sentences about what you have already done this week.',
    targetGrammarPoints: ['present perfect: hebben/zijn + past participle'],
  },
  {
    id: 'wp-a1-10',
    topicIds: ['a1-verbs-zijn-hebben'],
    promptText: 'Beschrijf jezelf en je familie met de werkwoorden "zijn" en "hebben".',
    promptTextEn: 'Describe yourself and your family using the verbs "zijn" and "hebben".',
    targetGrammarPoints: ['zijn and hebben conjugation'],
  },
  {
    id: 'wp-a1-11',
    topicIds: ['a1-modal-verbs'],
    promptText: 'Schrijf vier zinnen: iets wat je kunt, iets wat je wilt, iets wat je moet, en iets wat je mag doen.',
    promptTextEn: 'Write four sentences: something you can do, something you want to do, something you have to do, and something you are allowed to do.',
    targetGrammarPoints: ['modal verb + bare infinitive construction'],
  },
  {
    id: 'wp-a1-12',
    topicIds: ['a1-diminutives'],
    promptText: 'Beschrijf je favoriete kopje koffie of thee met minstens twee verkleinwoorden.',
    promptTextEn: 'Describe your favorite cup of coffee or tea using at least two diminutives.',
    targetGrammarPoints: ['diminutive formation (-je and its variants)'],
  },
  {
    id: 'wp-a1-13',
    topicIds: ['a1-conjunctions'],
    promptText: 'Verbind twee ideeen over je dag met "en", "maar", "want", "of" of "dus".',
    promptTextEn: 'Connect two ideas about your day using "en", "maar", "want", "of", or "dus".',
    targetGrammarPoints: ['coordinating conjunctions (no word-order change)'],
  },
  {
    id: 'wp-a1-14',
    topicIds: ['a1-adjectives'],
    promptText: 'Beschrijf je huis of kamer met minstens drie bijvoeglijke naamwoorden.',
    promptTextEn: 'Describe your house or room using at least three adjectives.',
    targetGrammarPoints: ['adjective -e agreement (de/het, definite/indefinite)'],
  },
];
