import { WordSeed } from '../a1/words';

export const a0Words: WordSeed[] = [
  // Greetings & politeness
  { id: 'w-hallo', nl: 'hallo', en: 'hello', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-dag', nl: 'dag', en: 'hi / bye (informal, either direction)', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-goedemorgen', nl: 'goedemorgen', en: 'good morning', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-goedemiddag', nl: 'goedemiddag', en: 'good afternoon', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-goedenavond', nl: 'goedenavond', en: 'good evening', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-goedenacht', nl: 'goedenacht', en: 'good night', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-tot-ziens', nl: 'tot ziens', en: 'goodbye (see you)', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-doei', nl: 'doei', en: 'bye (casual)', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-alsjeblieft', nl: 'alsjeblieft', en: 'please / here you go', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-dank-je-wel', nl: 'dank je wel', en: 'thank you', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-sorry', nl: 'sorry', en: 'sorry', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-pardon', nl: 'pardon', en: 'excuse me / pardon', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-ja', nl: 'ja', en: 'yes', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },
  { id: 'w-nee', nl: 'nee', en: 'no', themeId: 'theme-greetings', firstIntroducedTopicId: 'a0-greetings-intro' },

  // Numbers 0-20
  { id: 'w-num-0', nl: 'nul', en: 'zero', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-1', nl: 'een', en: 'one', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-2', nl: 'twee', en: 'two', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-3', nl: 'drie', en: 'three', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-4', nl: 'vier', en: 'four', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-5', nl: 'vijf', en: 'five', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-6', nl: 'zes', en: 'six', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-7', nl: 'zeven', en: 'seven', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-8', nl: 'acht', en: 'eight', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-9', nl: 'negen', en: 'nine', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-10', nl: 'tien', en: 'ten', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-11', nl: 'elf', en: 'eleven', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-12', nl: 'twaalf', en: 'twelve', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-13', nl: 'dertien', en: 'thirteen', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-14', nl: 'veertien', en: 'fourteen', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-15', nl: 'vijftien', en: 'fifteen', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-16', nl: 'zestien', en: 'sixteen', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-17', nl: 'zeventien', en: 'seventeen', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-18', nl: 'achttien', en: 'eighteen', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-19', nl: 'negentien', en: 'nineteen', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-20', nl: 'twintig', en: 'twenty', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-21', nl: 'eenentwintig', en: 'twenty-one', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },

  // Numbers: tens
  { id: 'w-num-30', nl: 'dertig', en: 'thirty', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-40', nl: 'veertig', en: 'forty', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-50', nl: 'vijftig', en: 'fifty', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-60', nl: 'zestig', en: 'sixty', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-70', nl: 'zeventig', en: 'seventy', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-80', nl: 'tachtig', en: 'eighty', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-90', nl: 'negentig', en: 'ninety', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },
  { id: 'w-num-100', nl: 'honderd', en: 'one hundred', themeId: 'theme-numbers', firstIntroducedTopicId: 'a0-numbers' },

  // Days of the week
  { id: 'w-maandag', nl: 'maandag', en: 'Monday', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-dinsdag', nl: 'dinsdag', en: 'Tuesday', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-woensdag', nl: 'woensdag', en: 'Wednesday', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-donderdag', nl: 'donderdag', en: 'Thursday', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-vrijdag', nl: 'vrijdag', en: 'Friday', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-zaterdag', nl: 'zaterdag', en: 'Saturday', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-zondag', nl: 'zondag', en: 'Sunday', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },

  // Months
  { id: 'w-januari', nl: 'januari', en: 'January', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-februari', nl: 'februari', en: 'February', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-maart', nl: 'maart', en: 'March', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-april', nl: 'april', en: 'April', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-mei', nl: 'mei', en: 'May', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-juni', nl: 'juni', en: 'June', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-juli', nl: 'juli', en: 'July', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-augustus', nl: 'augustus', en: 'August', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-september', nl: 'september', en: 'September', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-oktober', nl: 'oktober', en: 'October', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-november', nl: 'november', en: 'November', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-december', nl: 'december', en: 'December', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },

  // Relative time words
  { id: 'w-vandaag', nl: 'vandaag', en: 'today', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-morgen', nl: 'morgen', en: 'tomorrow', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-gisteren', nl: 'gisteren', en: 'yesterday', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-nu', nl: 'nu', en: 'now', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },
  { id: 'w-straks', nl: 'straks', en: 'in a bit / later', themeId: 'theme-time-calendar', firstIntroducedTopicId: 'a0-days-months' },

  // Colors
  { id: 'w-rood', nl: 'rood', en: 'red', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-blauw', nl: 'blauw', en: 'blue', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-geel', nl: 'geel', en: 'yellow', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-groen', nl: 'groen', en: 'green', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-wit', nl: 'wit', en: 'white', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-zwart', nl: 'zwart', en: 'black', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-bruin', nl: 'bruin', en: 'brown', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-oranje', nl: 'oranje', en: 'orange', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-roze', nl: 'roze', en: 'pink', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-paars', nl: 'paars', en: 'purple', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
  { id: 'w-grijs', nl: 'grijs', en: 'gray', themeId: 'theme-colors', firstIntroducedTopicId: 'a0-colors' },
];
