const { withProjectBuildGradle } = require('@expo/config-plugins');

// The default NDK version Expo's ExpoRootProjectPlugin picks (27.1.12297006)
// corresponds to an install on this machine that's corrupted/incomplete
// (missing source.properties, fails with CXX1101). NDK 30.0.14904198 is
// already installed and working here, so pin to it instead.
//
// This can't be done via app.json's expo.android.ndkVersion field or via
// expo-build-properties — neither is read by anything that sets the NDK
// version for this project. The only lever is android/build.gradle itself,
// and ExpoRootProjectPlugin uses extra.setIfNotExist("ndkVersion"), which
// only respects a value that's ALREADY present at apply-time. So the ext
// block below must land BEFORE both `apply plugin` lines, every time
// android/build.gradle is regenerated by `expo prebuild`.
const NDK_VERSION = '30.0.14904198';

module.exports = function withNdkVersionFix(config) {
  return withProjectBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error('withNdkVersionFix only supports Groovy build.gradle files');
    }

    let contents = config.modResults.contents;
    const marker = 'apply plugin: "expo-root-project"';

    if (contents.includes(`ndkVersion = "${NDK_VERSION}"`)) {
      // Already patched (idempotent - shouldn't normally happen since
      // prebuild regenerates the file from scratch, but just in case).
      return config;
    }

    if (!contents.includes(marker)) {
      throw new Error(
        `withNdkVersionFix: could not find "${marker}" in android/build.gradle - template may have changed.`
      );
    }

    const insert =
      `// Pin NDK to a version already installed on this machine — the default\n` +
      `// triggers a corrupted/incomplete download here. This must be set BEFORE\n` +
      `// both apply plugin lines below: ExpoRootProjectPlugin uses\n` +
      `// extra.setIfNotExist("ndkVersion"), which only respects a value that's\n` +
      `// already present at apply-time and ignores anything set afterward.\n` +
      `// (Injected automatically by plugins/withNdkVersionFix.js on every prebuild.)\n` +
      `ext {\n` +
      `    ndkVersion = "${NDK_VERSION}"\n` +
      `}\n\n`;

    contents = contents.replace(marker, insert + marker);
    config.modResults.contents = contents;
    return config;
  });
};
