import { WritingPrompt } from '../../data/types';

export const b1WritingPrompts: WritingPrompt[] = [
  {
    id: 'wp-b1-1',
    topicIds: ['b1-passive-voice'],
    promptText: 'Beschrijf een gebouw of product en hoe het gemaakt wordt, met minstens één zin in de lijdende vorm (worden of zijn + voltooid deelwoord).',
    promptTextEn: 'Describe a building or product and how it is made, using at least one passive-voice sentence (worden or zijn + past participle).',
    targetGrammarPoints: ['passive voice auxiliary choice (worden vs. zijn)'],
  },
  {
    id: 'wp-b1-2',
    topicIds: ['b1-conditional'],
    promptText: 'Schrijf drie zinnen over wat je zou doen als je een miljoen euro had, met "zou" of "zouden" in elke zin.',
    promptTextEn: 'Write three sentences about what you would do if you had a million euros, using "zou" or "zouden" in each sentence.',
    targetGrammarPoints: ['conditional formation (zou/zouden + infinitive)'],
  },
  {
    id: 'wp-b1-3',
    topicIds: ['b1-pluperfect'],
    promptText: 'Beschrijf een dag waarop iets al gebeurd was voordat iets anders gebeurde, met minstens twee zinnen in de voltooid verleden tijd.',
    promptTextEn: 'Describe a day when something had already happened before something else happened, using at least two pluperfect sentences.',
    targetGrammarPoints: ['pluperfect formation (had/was + past participle)'],
  },
  {
    id: 'wp-b1-4',
    topicIds: ['b1-aan-het-continuous'],
    promptText: 'Beschrijf wat verschillende mensen in jouw huis op dit moment aan het doen zijn, met minstens drie zinnen.',
    promptTextEn: 'Describe what different people in your house are doing right now, using at least three sentences.',
    targetGrammarPoints: ['aan het continuous formation (zijn + aan het + infinitive)'],
  },
  {
    id: 'wp-b1-5',
    topicIds: ['b1-short-subclauses'],
    promptText: 'Schrijf twee zinnen over je doelen met "om ... te" en één zin met "zonder ... te".',
    promptTextEn: 'Write two sentences about your goals using "om ... te" and one sentence using "zonder ... te".',
    targetGrammarPoints: ['te + infinitive after om/zonder/in plaats van'],
  },
  {
    id: 'wp-b1-6',
    topicIds: ['b1-imperative'],
    promptText: 'Schrijf een kort recept of instructie van vier stappen met de gebiedende wijs.',
    promptTextEn: 'Write a short recipe or set of instructions with four steps using the imperative.',
    targetGrammarPoints: ['imperative formation (jij-form without -t)'],
  },
  {
    id: 'wp-b1-7',
    topicIds: ['b1-pronominal-adverbs-advanced'],
    promptText: 'Beschrijf je stad met minstens één zin die begint met "Er is" of "Er zijn", en gebruik ook het woordje "er" om iets te vervangen.',
    promptTextEn: 'Describe your city using at least one sentence that starts with "Er is" or "Er zijn", and also use "er" to replace something.',
    targetGrammarPoints: ['existential/locative/quantitative "er"'],
  },
  {
    id: 'wp-b1-8',
    topicIds: ['b1-genitive-relative-pronouns'],
    promptText: 'Beschrijf iemand die je kent met een zin die "wiens" of "van wie" gebruikt, en een zin met "wie" na een voorzetsel.',
    promptTextEn: 'Describe someone you know with a sentence using "wiens" or "van wie", and a sentence using "wie" after a preposition.',
    targetGrammarPoints: ['genitive relative pronouns (wiens/van wie) and prepositional "wie"'],
  },
  {
    id: 'wp-b1-9',
    topicIds: ['b1-word-order-advanced'],
    promptText: 'Schrijf twee zinnen waarin je iets aan iemand geeft of laat zien, met de voornaamwoorden zo vroeg mogelijk in de zin.',
    promptTextEn: 'Write two sentences where you give or show something to someone, placing the pronouns as early as possible in the sentence.',
    targetGrammarPoints: ['reduced pronoun placement and postpositions'],
  },
  {
    id: 'wp-b1-10',
    topicIds: ['b1-compound-nouns'],
    promptText: 'Maak drie nieuwe samengestelde zelfstandige naamwoorden met woorden die je al kent, en gebruik elk in een zin.',
    promptTextEn: 'Create three new compound nouns using words you already know, and use each in a sentence.',
    targetGrammarPoints: ['compound noun formation and article agreement with the final noun'],
  },
  {
    id: 'wp-b1-11',
    topicIds: ['b1-possessives-advanced'],
    promptText: 'Schrijf een kort gesprek van vier zinnen waarin je vraagt van wie iets is, met minstens één zelfstandig bezittelijk voornaamwoord (de mijne, het onze) en één met "van".',
    promptTextEn: 'Write a short four-sentence conversation asking whose something is, using at least one independent possessive (de mijne, het onze) and one with "van".',
    targetGrammarPoints: ['independent possessive forms and the colloquial "van" alternative'],
  },
  {
    id: 'wp-b1-12',
    topicIds: ['b1-indefinite-numbers-and-exclamatives'],
    promptText: 'Schrijf drie zinnen over je week met "een paar", "veel" of "weinig", en eindig met een uitroep met "wat een" of "zo\'n".',
    promptTextEn: 'Write three sentences about your week using "een paar", "veel", or "weinig", and end with an exclamation using "wat een" or "zo\'n".',
    targetGrammarPoints: ['indefinite quantity words and exclamative pronouns'],
  },
  {
    id: 'wp-b1-13',
    topicIds: ['b1-hen-hun-and-reciprocal'],
    promptText: 'Beschrijf twee vrienden en hoe zij elkaar hebben leren kennen, met "hen" of "hun" en met "elkaar" in je tekst.',
    promptTextEn: 'Describe two friends and how they met, using "hen" or "hun" and "elkaar" in your text.',
    targetGrammarPoints: ['hen vs. hun and the reciprocal pronoun elkaar'],
  },
  {
    id: 'wp-b1-14',
    topicIds: ['b1-modal-verbs-perfect-tense'],
    promptText: 'Schrijf drie zinnen over dingen die je wel of niet hebt kunnen, moeten, of mogen doen, in de voltooid tegenwoordige tijd.',
    promptTextEn: 'Write three sentences about things you have or have not been able to, had to, or been allowed to do, in the perfect tense.',
    targetGrammarPoints: ['IPP double-infinitive construction for modal verbs in the perfect tense'],
  },
];
